### ISSUE TITLE
Code Review (backend)

### ISSUE THREAD

**Issue by nartc** [tiennampham23/nodejs-angular-typescript-boilerplate#1]
- https://github.com/tiennampham23/nodejs-angular-typescript-boilerplate/blob/master/api/src/app.ts#L2
Express 4 has `bodyParser` built-in (it just uses `body-parser` under the hood) but this can be removed and use `express.json()` and `express.urlencoded()` instead.

- https://github.com/tiennampham23/nodejs-angular-typescript-boilerplate/blob/master/api/src/constants/httpCode.ts#L1
Use standard HTTP Code instead. `OK: 200`, `CREATED: 201`, `UNAUTHORIZED: 401` etc...

- https://github.com/tiennampham23/nodejs-angular-typescript-boilerplate/blob/master/api/src/constants/ignorePath.ts
This feels redundant. This should be setup on the Angular's interceptors side.

- https://github.com/tiennampham23/nodejs-angular-typescript-boilerplate/blob/master/api/src/repositories/user.repository.ts#L8
the `interfaces` pattern does not really make sense here. This seems like a redundant abstraction which just requires the consumers to write more code without giving any values at all. Interfaces in TypeScript is pretty weak and does not pertain anything. I'd suggest removing the Interface altogether because as far as IoC cares, you can always provide a different providers for different environments (testing)

-

**Comment by tiennampham23** [comment]
Thanks you for reviewing my project, I'll upgrade the project as soon as
