### ISSUE TITLE
About Exception Handler

### ISSUE THREAD

**Issue by leducthang98** [tiennampham23/nodejs-angular-typescript-boilerplate#2]
Ví dụ như JavaSpring thì nó có thằng ControllerAdvice chuyên để handler exception, hoặc .NET nó có onException ấy, vậy nếu làm bằng .ts kiểu OOP như này thì mình handler nó ở đâu thế ông? :D

**Comment by tiennampham23** [comment]
@leducthang98 Thắng có thể dùng middleware như này:
https://wanago.io/2018/12/17/typescript-express-error-handling-validation/

**Comment by leducthang98** [comment]
Ồ, vậy là vẫn sẽ sử dụng Middleware kiểu Functional giống như code js ^^

**Comment by leducthang98** [comment]
Okie cảm ơn nhé!

**Comment by tiennampham23** [comment]
Ông viết function đó sang kiểu Middleware dạng class cũng được, tác giả họ viết functional thôi.
